name: build-and-push

on:
    release:
        types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    - name: Get the version
      run: echo ::set-env name=TAG_ID::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile -t sturrent/dns-perf-test:"${{ env.TAG_ID }}"
    - name: Push the tagged Docker image
      run: docker push sturrent/dns-perf-test:"${{ env.TAG_ID }}"
    - name: Tag the latest Docker image
      run: docker tag sturrent/dns-perf-test:"${{ env.TAG_ID }}" sturrent/dns-perf-test:latest
    - name: Push the latest Docker image
      run: docker push sturrent/dns-perf-test:latest
